// Architectural drawing standing in for the floor plan file the museum uploads.
export function FloorPlanSvg({ className = '' }: { className?: string }) {
  return (
    <svg viewBox="0 0 820 620" className={className} role="img" aria-label="Exhibition floor plan">
      <rect width="820" height="620" fill="#fbfcfe" />
      {Array.from({ length: 20 }, (_, i) => (
        <line key={`v${i}`} x1={i * 41} y1="0" x2={i * 41} y2="620" stroke="#e4ebf3" strokeWidth="1" />
      ))}
      {Array.from({ length: 15 }, (_, i) => (
        <line key={`h${i}`} x1="0" y1={i * 41} x2="820" y2={i * 41} stroke="#e4ebf3" strokeWidth="1" />
      ))}

      {/* outer walls with entrance opening at bottom centre */}
      <rect x="45" y="45" width="730" height="530" fill="#ffffff" />
      <path
        d="M455 575 L775 575 L775 45 L45 45 L45 575 L365 575"
        fill="none"
        stroke="#33415c"
        strokeWidth="7"
        strokeLinecap="square"
      />
      {/* central gallery block */}
      <path
        d="M150 165 L660 165 L660 460 L235 460 L235 400 L185 400 L185 330 L150 330 Z"
        fill="#eef2f8"
        stroke="#33415c"
        strokeWidth="5"
      />

      {/* display cases along the corridor */}
      {[
        [95, 105],
        [255, 105],
        [415, 105],
        [575, 105],
        [710, 210],
        [710, 340],
        [710, 470],
        [95, 470],
        [330, 505],
        [520, 505],
      ].map(([x, y]) => (
        <rect key={`${x}-${y}`} x={x} y={y} width="42" height="24" fill="#ffffff" stroke="#7c8db0" strokeWidth="3" />
      ))}

      <text x="405" y="320" textAnchor="middle" fill="#33415c" fontSize="22" fontWeight="700" fontFamily="Inter, sans-serif">
        Gallery 1.3
      </text>
      <text x="405" y="348" textAnchor="middle" fill="#7c8db0" fontSize="15" fontFamily="Inter, sans-serif">
        The Archaeology of the Netherlands
      </text>
      <text x="410" y="602" textAnchor="middle" fill="#33415c" fontSize="15" fontWeight="700" fontFamily="Inter, sans-serif">
        ↑ Entrance
      </text>

      {/* north arrow + scale bar */}
      <g stroke="#33415c" strokeWidth="3" fill="none">
        <line x1="60" y1="590" x2="200" y2="590" />
        <line x1="60" y1="584" x2="60" y2="596" />
        <line x1="200" y1="584" x2="200" y2="596" />
      </g>
      <text x="130" y="580" textAnchor="middle" fill="#7c8db0" fontSize="12" fontFamily="Inter, sans-serif">
        10 m
      </text>
      <g transform="translate(770, 585)">
        <path d="M0 8 L6 -12 L12 8 L6 3 Z" fill="#33415c" />
        <text x="6" y="24" textAnchor="middle" fill="#33415c" fontSize="12" fontWeight="700" fontFamily="Inter, sans-serif">
          N
        </text>
      </g>
    </svg>
  );
}

// Hand-drawn empty treasure map "generated by AI" from the floor plan,
// in the style of the visitor app map assets.
export function EmptyMapSvg({ className = '' }: { className?: string }) {
  return (
    <svg viewBox="0 0 1200 1050" className={className} role="img" aria-label="Empty treasure map">
      <rect width="1200" height="1050" fill="#fdf8ec" />
      {/* outer wall, open at the bottom centre for the entrance */}
      <path
        d="M660 905 L1183 897 L1080 18 L18 100 L132 910 L540 906"
        fill="none"
        stroke="#5a4a2f"
        strokeWidth="15"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      {/* central gallery block with a stepped notch, echoing the floor plan */}
      <path
        d="M152 255 L968 210 L1018 745 L232 782 L224 702 L182 705 L176 622 L216 618 Z"
        fill="#fdf8ec"
        stroke="#5a4a2f"
        strokeWidth="11"
        strokeLinejoin="round"
      />
      {/* entrance arrow */}
      <g stroke="#5a4a2f" strokeWidth="9" strokeLinecap="round" fill="none">
        <line x1="600" y1="990" x2="600" y2="925" />
        <path d="M578 950 L600 925 L622 950" />
      </g>
      <text
        x="600"
        y="1032"
        textAnchor="middle"
        fill="#5a4a2f"
        fontSize="42"
        fontStyle="italic"
        fontWeight="700"
        fontFamily="'Segoe Script', 'Bradley Hand', 'Comic Sans MS', cursive"
      >
        Entrance
      </text>
    </svg>
  );
}
